export const User = {
    SET_USER:"SET_USER",
    SELECTED_USER:"SELECTED_USER",
    DELETE_USER:"DELETED_USER",
    GET_USER:"GET_USER"
}
export const POST={
    ALL_POST:"ALL_POST",
    GET_SELECTED_POST:"GET_SELECTED_POST",
    DELETE_SELECTED_POST:"DELETE_SELECTED_POST",
    EDIT_SELECTED_POST:"EDIT_SELECTED_POST"
}